name: Baseline Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  baseline:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run -w @bdc/cli build
      - name: Run Baseline Dev Coach
        id: bdc
        run: |
          node packages/cli/dist/index.js --path . --format json > bdc-report.json || true
          echo "report<<EOF" >> $GITHUB_OUTPUT
          cat bdc-report.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const report = JSON.parse(process.env.REPORT_JSON || core.getInput('report-json') || `${{ steps.bdc.outputs.report }}`);
            const lines = [];
            lines.push(`## 🧭 Baseline Dev Coach Report`);
            lines.push(`**Files scanned:** ${report.filesScanned}  |  **Findings:** ${report.findings.length}`);
            for (const f of report.findings.slice(0, 30)) {
              lines.push(`- \`${f.file}:${f.line}\` **${f.featureName}** (id: \`${f.featureId}\`) — Baseline: \`${f.baseline}\``);
            }
            if (report.findings.length > 30) lines.push(`…and ${report.findings.length - 30} more`);
            const body = lines.join("\n");
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
        env:
          REPORT_JSON: ${{ steps.bdc.outputs.report }}
